version: '3.8'

services:
  payment-service:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=gopaydb

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: gopaydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
