basePath: /api/v1
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.PaymentRequest:
    properties:
      amount:
        type: number
      from_account:
        type: string
      to_account:
        type: string
    type: object
  models.PaymentResponse:
    properties:
      amount:
        type: number
      created_at:
        type: string
      id:
        type: integer
      status:
        type: string
    type: object
host: localhost:8084
info:
  contact:
    email: support@paymentapi.com
    name: API Support
  description: API for processing payments with JWT authentication
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Payment Service API
  version: "1.0"
paths:
  /api/v1/pay:
    post:
      consumes:
      - application/json
      description: Process a payment transaction
      parameters:
      - description: Payment details
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/models.PaymentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.PaymentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Process payment
      tags:
      - payments
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
